name: OpenSSF Scorecard

on:
  branch_protection_rule:
  push:
    branches: [main, master]
  schedule:
    - cron: '31 9 * * 2'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scorecard:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      security-events: write
      id-token: write
    steps:
      - name: Run Scorecard
        uses: ossf/scorecard-action@v2.4.3
        with:
          results_file: scorecard-results.sarif
          results_format: sarif
          publish_results: true

      - name: Upload Scorecard artifact
        uses: actions/upload-artifact@v7
        with:
          name: scorecard-results
          path: scorecard-results.sarif
